apiVersion: v1
kind: Secret
metadata:
  name: openai-secret
type: Opaque
data:
  api-key: c2stcHJvai1GeWpBTWNyZlBub3dPaXF1dHV6ZkxkaHgybW5wTHBhcGw2VHRESzlWWWtOQlVzNEhkeUJXSzNEOVhRc2ZtS1lsendINUlaS09WalQzQmxia0ZKMGZ2WDFuR0ZWSGJndFJuamMtZlc4ZTdNeWVVZTUyVUtqcGlYMVd0aGlIMUN3SXNMWDU5NzczQ0hNME1mYnFqSExuOUw1eDVub0E=   # <-- your base64 encoded key
